server:
  port: 8002
  servlet:
    context-path: /web
spring:
  application:
    name: web
  cloud:
    nacos:
      discovery:
        enabled: true
        namespace: 77d3b4df-97fc-4254-b2a2-b2b13711b469
        group: liufeng
        server-addr: localhost:8848
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-idle: 4
    timeout: 6000
    database: 0
logging:
  level:
    com:
      my:
        liufeng:
          auth:
            RemoteUserService: DEBUG

liufeng:
  provider:
    controllerLog: true
  consumer: true